// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package tutorial

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Author struct {
	ID   int64
	Name string
	Bio  sql.NullString
}

type User struct {
	ID          uuid.NullUUID
	Username    sql.NullString
	TenantID    sql.NullString
	CreatedTime time.Time
}
